[package]
name = "replay"
version = "0.1.0"
authors = ["Jonathan Tran <jonnytran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
find_folder = "0.3.0"
gfx_device_gl = "0.16.2"
piston_window = "0.106.0"
